version: "3.8"
services:
  webserver:
    build: .
    ports:
      - "3033:3033"  # Single exposed port for everything
    networks:
      - app_network

  wetty:
    image: wettyoss/wetty
    command: --ssh-host=172.105.94.208
    networks:
      - app_network

networks:
  app_network: