version: "3.8"
services:
  webserver:
    build: .  # Builds your custom Nginx Dockerfile
    ports:
      - "8000:8000"  # Single exposed port for everything
    networks:
      - web_network

  wetty:
    image: wettyoss/wetty
    command: --ssh-host=172.105.94.208 --port=3033
    networks:
      - web_network

networks:
  web_network:
    external: true